import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BottomMenu from "@/components/bottom-menu";
import ToastProvider from "@/components/toast-provider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <div className="w-full max-w-lg mx-auto flex flex-col min-h-screen sm:border-l sm:border-r border-primary">
                    <ToastProvider />
                    {children}
                    <div className="mt-auto flex flex-wrap items-center justify-center px-4 py-1 bg-primary">
                        <p className="text-center text-[10px]">created by kuff</p>
                    </div>
                    {/* <BottomMenu /> */}
                </div>
            </body>
        </html>
    );
}
